In [12]:
import h5py
import numpy as np
CRYSTAL = h5py.File('EELS_3D-out/EELS_3D_sym-ex.h5')
EMPTY = h5py.File('EELS_3D-out/EELS_3D_EMPTY_PML_a36-ex.h5')

In [13]:
q_e = 1.60217646e-19

In [14]:
Esim_crystal    = CRYSTAL['ex']     # NOT normalized E field in MEEP units
FLUXsim_crystal = CRYSTAL['flux']   # Electric field flux in MEEP units
Esim_empty      = EMPTY['ex']       # NOT normalized E field in MEEP units
FLUXsim_empty   = EMPTY['flux']     # Electric field flux in MEEP units

In [15]:
crystal = Esim_crystal[()]
empty   = Esim_empty[()]

In [16]:
# Normalization factor alpha
alpha_crystal = -q_e/FLUXsim_crystal[()]
alpha_empty   = -q_e/FLUXsim_empty[()]

crystal = alpha_crystal*Esim_crystal[()]    # Electric field for 1 electron in MEEP units
empty   = alpha_empty*Esim_empty[()]        # Electric field for 1 electron in MEEP units

In [17]:
crystal

array([[ 1.77141005e-18,  1.91827409e-18,  1.87284297e-18, ...,
        -5.24467424e-20, -4.56620698e-20, -4.86465323e-20],
       [-1.91407581e-18, -7.86098611e-19,  9.36506197e-19, ...,
         8.73352691e-20,  7.75641956e-20,  7.37729955e-20],
       [-1.32179840e-18, -1.68068568e-18, -2.41863290e-18, ...,
         4.32876604e-20,  4.45150471e-20,  5.72434120e-20],
       ...,
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
         1.93222208e-18,  2.02896732e-18,  2.10255541e-18],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
        -1.18624781e-18,  1.83026547e-19,  1.41867467e-18],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
        -1.43967941e-18, -1.95624088e-18, -2.33813456e-18]],
      shape=(866, 3152))

In [18]:
empty

array([[ 1.80400114e-18,  1.94881745e-18,  1.91015940e-18, ...,
        -5.70733667e-20, -5.63229861e-20, -5.98885185e-20],
       [-1.88307034e-18, -7.59948195e-19,  9.47681740e-19, ...,
         7.81289518e-20,  7.70452484e-20,  8.18516899e-20],
       [-1.35078433e-18, -1.70049468e-18, -2.41873713e-18, ...,
         5.60196725e-20,  5.52911199e-20,  5.88035205e-20],
       ...,
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
         1.89314207e-18,  1.99239815e-18,  2.06512124e-18],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
        -1.24528761e-18,  1.10647648e-19,  1.32048182e-18],
       [-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, ...,
        -1.54852770e-18, -2.05229729e-18, -2.42766143e-18]],
      shape=(866, 3152))

In [19]:
diff = crystal - empty  # Eind in MEEP units
diff

array([[-3.25910893e-20, -3.05433590e-20, -3.73164293e-20, ...,
         4.62662422e-21,  1.06609163e-20,  1.12419863e-20],
       [-3.10054659e-20, -2.61504157e-20, -1.11755429e-20, ...,
         9.20631738e-21,  5.18947203e-22, -8.07869433e-21],
       [ 2.89859249e-20,  1.98090045e-20,  1.04230936e-22, ...,
        -1.27320121e-20, -1.07760728e-20, -1.56010849e-21],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         3.90800101e-20,  3.65691672e-20,  3.74341625e-20],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         5.90398024e-20,  7.23788988e-20,  9.81928540e-20],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         1.08848282e-19,  9.60564121e-20,  8.95268701e-20]],
      shape=(866, 3152))

In [20]:
with h5py.File("crystal_PML_a36-r245-ex.hdf5", "w") as f:
    dset = f.create_dataset("ex", empty.shape, dtype='<f8', data=crystal)

In [10]:
with h5py.File("empty_PML_a36-ex.hdf5", "w") as f:
    dset = f.create_dataset("ex", crystal.shape, dtype='<f8', data=empty)

In [11]:
with h5py.File("diff_PML_a36-r245.hdf5", "w") as f:
    dset = f.create_dataset("ex", diff.shape, dtype='<f8', data=diff)